name: Python Package Build
run-name: Python Package build by ${{ github.actor }}
on: [push]
jobs:
  Python-Package-Build:
    runs-on: ubuntu-latest
    container: 
      image: python:3.12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: ownership workaround
        run: git config --system --add safe.directory '*'
      - name: Build package with Poetry
        run: |
          pip install poetry
          poetry build
  Python-Package-Stylecheck:
    runs-on: ubuntu-latest
    container: python:3.12
    needs: Python-Package-Build
    steps:
      - name: Run linters
        run: |
          echo "This step should run linters and typecheckers"
          ls
  Python-Package-Release:
    runs-on: ubuntu-latest
    container: python:3.12
    needs: [Python-Package-Build, Python-Package-Stylecheck]
    steps:
      - name: Upload package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-package
          path: dist/
      
      