name: Python Package Build
run-name: Python Package bulid by ${{ github.actor }}
on: [push]
jobs:
  Python-Package-Build:
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build package with Poetry
        run: |
          pip install poetry
          poetry build
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Upload package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-package
          path: dist/
      
      